In [ ]:
!pip install nltk scikit-learn regex numpy pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
import numpy as np
import nltk 
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import re
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
df = pd.read_csv('Resources/emails.csv')
df.head()

Text  Spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [ ]:
df.Spam.value_counts()

0    4360
1    1368
Name: Spam, dtype: int64

In [ ]:


corpus=[]

for i in range(len(df)):
    # removing all non-alphanumeric characters
    message=re.sub('[^a-zA-Z0-9]',' ',df['Text'][i]) 
    # converting the message to lowercase
    message=message.lower()
    message = message.split()
    
               
    corpus.append(message) 

In [ ]:
print(len(corpus))

5728


In [ ]:
df.head()

Text  Spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [ ]:
print(len(corpus))

5728


In [ ]:
cv=CountVectorizer(max_features=2500,ngram_range=(1,3))
cvfit=cv.fit(corpus)
X = cvfit.transform(corpus).toarray()
y=df['Spam']

In [ ]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
import pickle
with open("pickle2.pkl","wb") as f:
    pickle.dump(cvfit, f)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.20,random_state=1,stratify=y)

In [ ]:
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  100
hidden_nodes_layer2 = 200
hidden_nodes_layer3 = 50

In [ ]:
import tensorflow as tf

In [ ]:
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, activation="relu", input_dim=number_input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 100)               250100    
                                                                 
 dense_9 (Dense)             (None, 200)               20200     
                                                                 
 dense_10 (Dense)            (None, 50)                10050     
                                                                 
 dense_11 (Dense)            (None, 1)                 51        
                                                                 
Total params: 280,401
Trainable params: 280,401
Non-trainable params: 0
_________________________________________________________________


In [ ]:
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
fit_model = nn.fit(X_train, y_train, epochs=50)

Epoch 1/50
144/144 [==============================] - 2s 6ms/step - loss: 0.2159 - accuracy: 0.9171
Epoch 2/50
144/144 [==============================] - 1s 6ms/step - loss: 0.0297 - accuracy: 0.9948
Epoch 3/50
144/144 [==============================] - 1s 6ms/step - loss: 0.0127 - accuracy: 0.9985
Epoch 4/50
144/144 [==============================] - 1s 6ms/step - loss: 0.0053 - accuracy: 0.9996
Epoch 5/50
144/144 [==============================] - 1s 7ms/step - loss: 0.0038 - accuracy: 0.9993
Epoch 6/50
144/144 [==============================] - 1s 8ms/step - loss: 0.0029 - accuracy: 0.9996
Epoch 7/50
144/144 [==============================] - 1s 6ms/step - loss: 0.0024 - accuracy: 0.9996
Epoch 8/50
144/144 [==============================] - 1s 6ms/step - loss: 0.0021 - accuracy: 0.9993
Epoch 9/50
144/144 [==============================] - 1s 6ms/step - loss: 0.0019 - accuracy: 0.9993
Epoch 10/50
144/144 [==============================] - 1s 6ms/step - loss: 0.0016 - accuracy: 0.9996

In [ ]:
model_loss, model_accuracy = nn.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

36/36 - 0s - loss: 0.0680 - accuracy: 0.9887 - 204ms/epoch - 6ms/step
Loss: 0.06797780841588974, Accuracy: 0.988656222820282


In [ ]:
nn.save("success1.h5")

In [ ]:
new_text = "Subject: fpa notice : ebay misrepresentation of identity - user suspension - section 9 -  dear ebay member ,  in an effort to protect your ebay  account security , we have suspended your account until such time that it can  be safely restored to you . we have taken this action because your account  may have been compromised . although we cannot disclose our investigative  procedures that led to this conclusion , please know that we took this action  in order to maintain the safety of your account . for instructions on  getting your account reinstated , please click the button bellow :  thank you for your patience and  cooperation . regards ,  safeharbor departmentebay  inc . "

In [ ]:
new_corpus=[]

message=re.sub('[^a-zA-Z0-9]',' ',new_text) 
  
message=message.lower() 
               
new_corpus.append(message) 

In [ ]:
ham_message = "Subject: meeting with vince set for 1 pm monday , april 17  maureen , thank you very much for taking time away from your project to talk  with me this morning . since the management decision to close info central , i  have been doing small projects that , while necessary , do not require my  education , knowledge or research capabilities .  i appreciate your suggestion that i speak to vince since i am anxious to  return to contributing at a higher level . i am attaching my resume in the  hope that it will trigger ideas for possible ways that i can use my abilities  in the research department . i have worked as an information specialist for  14 years , doing research for people at all levels in both the pharmaceutical  and energy industries . i have focused most heavily on business research , but  learn quickly and can branch out in whatever direction necessary for a  project .  i ' m looking forward to meeting with vince on monday afternoon . thanks again  for your help ."

In [ ]:
new_corpus = []
def preprocess(text): 
  message=re.sub('[^a-zA-Z0-9]',' ',text) 
  
  message=message.lower() 
               
  new_corpus.append(message) 

In [ ]:
preprocess(ham_message)

In [ ]:
ham_x = cvfit.transform(new_corpus)

In [ ]:
nn.predict(ham_x)

1/1 [==============================] - 0s 21ms/step


array([[3.5445446e-05]], dtype=float32)

In [ ]:
spam_message = "Subject: mail receipt  thank you for your mail regarding our site . we will reply as soon as possible . in the meantime please continue to enjoy our site .  tight lines  bray sea anglers ."

In [ ]:
spam = np.asarray(spam_message)

In [ ]:
print(spam)

Subject: mail receipt  thank you for your mail regarding our site . we will reply as soon as possible . in the meantime please continue to enjoy our site .  tight lines  bray sea anglers .


In [ ]:
preprocess(spam_message)

In [ ]:
spam_x = cvfit.transform(new_corpus)

In [ ]:
nn.predict(spam_x)

1/1 [==============================] - 0s 17ms/step


array([[3.544541e-05],
       [9.995594e-01]], dtype=float32)